# Generated by Django 3.2.4 on 2021-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersmodels',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='Age'),
        ),
    ]
