# Generated by Django 3.2.4 on 2021-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.PositiveBigIntegerField(default=18, verbose_name='Age')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
