# Generated by Django 3.2.4 on 2021-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='age')),
                ('position', models.CharField(max_length=30, verbose_name='position')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
