# Generated by Django 3.2.4 on 2021-06-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesmodels',
            options={},
        ),
        migrations.AlterModelTable(
            name='employeesmodels',
            table='employees',
        ),
    ]
